services:
  - type: web
    name: hostel-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ap-project-v67b.onrender.com