services:
  - type: web
    name: hostel-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: DATABASE_URL
        value: postgresql://hostel_database_6v9w_user:2pjYEiyIXTcLldfE33t8lk64RlUiVkjX@dpg-d72cbmbuibrs73b9ikbg-a.oregon-postgres.render.com/hostel_database_6v9w
      - key: JWT_SECRET
        value: hostel_jwt_secret_key_2024